minimumReleaseAgeExclude:
  - '@vue/compiler-core@3.5.38'
  - '@vue/compiler-dom@3.5.38'
  - '@vue/compiler-sfc@3.5.38'
  - '@vue/compiler-ssr@3.5.38'
  - '@vue/reactivity@3.5.38'
  - '@vue/runtime-core@3.5.38'
  - '@vue/runtime-dom@3.5.38'
  - '@vue/server-renderer@3.5.38'
  - '@vue/shared@3.5.38'
  - astro@6.4.6
  - vue@3.5.38
onlyBuiltDependencies:
  - esbuild
  - sharp
verifyDepsBeforeRun: false
