package handlers

import (
	"encoding/json"
	"net/http"

	"browser-server/internal/models"
)

func GetRoutes(w http.ResponseWriter, r *http.Request) {
	routes := []models.Route{
		{Method: "POST", Path: "/api/routes", Description: "List all available routes"},
		{Method: "GET", Path: "/api/ai/config", Description: "Get sanitized AI configuration and model catalog"},
		{Method: "GET", Path: "/api/ai/voice/config", Description: "Get sanitized AI voice typing configuration"},
		{Method: "GET", Path: "/api/ai/voice/transcribe", Description: "Open an authenticated voice transcription WebSocket"},
		{Method: "GET", Path: "/api/ai/voices/config", Description: "Get sanitized AI text-to-speech providers, models, and voices"},
		{Method: "GET", Path: "/api/ai/voices", Description: "List generated speech clips (param: limit)"},
		{Method: "POST", Path: "/api/ai/voices", Description: "Generate speech from text (body: text, provider, model, voice)"},
		{Method: "GET", Path: "/api/ai/voices/{id}/file", Description: "Stream a generated speech MP3"},
		{Method: "DELETE", Path: "/api/ai/voices/{id}", Description: "Delete a generated speech clip"},
		{Method: "GET", Path: "/api/ai/logs", Description: "List AI provider and correlated tool audit logs (filters: source, status, conversation_id, task_id, limit, offset)"},
		{Method: "GET", Path: "/api/ai/monitoring", Description: "Get AI request, tool, token, error, and latency metrics (param: window_hours)"},
		{Method: "GET", Path: "/api/ai/conversations", Description: "List AI conversations (params: q, limit)"},
		{Method: "POST", Path: "/api/ai/conversations", Description: "Create an AI conversation"},
		{Method: "GET", Path: "/api/ai/conversations/{id}", Description: "Get an AI conversation with messages"},
		{Method: "PATCH", Path: "/api/ai/conversations/{id}", Description: "Rename or change model for an AI conversation"},
		{Method: "DELETE", Path: "/api/ai/conversations/{id}", Description: "Delete an AI conversation"},
		{Method: "POST", Path: "/api/ai/conversations/{id}/messages", Description: "Send a message to an AI conversation (optional attachment_ids)"},
		{Method: "POST", Path: "/api/ai/conversations/{id}/attachments", Description: "Upload one staged image attachment (multipart: file)"},
		{Method: "DELETE", Path: "/api/ai/conversations/{id}/attachments/{attachmentId}", Description: "Cancel a staged image attachment"},
		{Method: "GET", Path: "/api/ai/attachments", Description: "List attached image attachments across conversations (params: limit)"},
		{Method: "GET", Path: "/api/ai/conversations/{id}/attachments/{attachmentId}", Description: "Get an attached image with content type and cache headers"},
		{Method: "POST", Path: "/api/ai/conversations/{id}/tool-calls/{callID}", Description: "Allow or reject a pending AI tool call"},
		{Method: "POST", Path: "/api/ai/conversations/{id}/stop", Description: "Cancel active AI generation for a conversation"},
		{Method: "POST", Path: "/api/ai/conversations/{id}/regenerate", Description: "Supersede and regenerate the latest AI response"},
		{Method: "POST", Path: "/api/ai/tasks", Description: "Enqueue a durable background AI task (body: prompt, conversation_id, max_attempts)"},
		{Method: "GET", Path: "/api/ai/tasks", Description: "List background AI tasks (params: status, limit)"},
		{Method: "GET", Path: "/api/ai/tasks/status", Description: "Get background AI task runner status and queue depth by status"},
		{Method: "GET", Path: "/api/ai/tasks/{id}", Description: "Get a background AI task with attempts and last error"},
		{Method: "DELETE", Path: "/api/ai/tasks/{id}", Description: "Delete a completed or failed background AI task"},
		{Method: "POST", Path: "/api/ai/tasks/{id}/cancel", Description: "Cancel a queued background AI task"},
		{Method: "GET", Path: "/api/search/omnibox", Description: "Search bookmark and grouped history suggestions for Chrome omnibox (params: user_id, q, limit)"},
		{Method: "GET", Path: "/api/todos", Description: "Get active or archived todos (filters: user_id, domain, completed, priority, tag, parent_id, archived; sort, order; pinned first)"},
		{Method: "POST", Path: "/api/todos", Description: "Create a new todo"},
		{Method: "GET", Path: "/api/todos/{id}", Description: "Get todo by ID (includes subtasks)"},
		{Method: "PUT", Path: "/api/todos/{id}", Description: "Update todo by ID"},
		{Method: "DELETE", Path: "/api/todos/{id}", Description: "Delete todo by ID"},
		{Method: "POST", Path: "/api/todos/reorder", Description: "Batch reorder todos (body: { items: [{ id, position }] })"},
		{Method: "GET", Path: "/api/todos/{id}/subtasks", Description: "Get subtasks for a todo"},
		{Method: "POST", Path: "/api/todos/{id}/subtasks", Description: "Create a subtask for a todo"},
		{Method: "POST", Path: "/api/screenshots", Description: "Upload a screenshot for a todo (multipart: file + ?todo_id=)"},
		{Method: "GET", Path: "/api/screenshots/{id}", Description: "Get screenshot PNG by todo ID"},
		{Method: "GET", Path: "/api/bookmarks", Description: "Get all bookmarks (filter: user_id, tags)"},
		{Method: "POST", Path: "/api/bookmarks", Description: "Create a new bookmark"},
		{Method: "GET", Path: "/api/bookmarks/{id}", Description: "Get bookmark by ID"},
		{Method: "PUT", Path: "/api/bookmarks/{id}", Description: "Update bookmark by ID"},
		{Method: "DELETE", Path: "/api/bookmarks/{id}", Description: "Delete bookmark by ID"},
		{Method: "POST", Path: "/api/bookmarks/import", Description: "Import bookmarks from Chrome HTML export"},

		{Method: "GET", Path: "/api/history", Description: "Get browsing history (filter: user_id, url)"},
		{Method: "GET", Path: "/api/history/grouped", Description: "Get URL-grouped, searched, paginated history (params: user_id, domain, q, column, limit, offset)"},
		{Method: "GET", Path: "/api/history/domains", Description: "Get history domain summaries ordered by visit count (params: user_id, q)"},
		{Method: "POST", Path: "/api/history", Description: "Add history entry"},
		{Method: "POST", Path: "/api/history/import", Description: "Import history from Chrome History SQLite file"},
		{Method: "GET", Path: "/api/history/{id}", Description: "Get history entry by ID"},
		{Method: "DELETE", Path: "/api/history/{id}", Description: "Delete history entry by ID"},
		{Method: "POST", Path: "/api/analytics/usage", Description: "Batch upsert domain usage time entries"},
		{Method: "GET", Path: "/api/analytics/summary", Description: "Get domain usage summary (filters: user_id, start_date, end_date, group_by, limit)"},
		{Method: "GET", Path: "/api/wallet", Description: "Get wallet entries without passwords (filter: user_id, website)"},
		{Method: "POST", Path: "/api/wallet", Description: "Create wallet entry"},
		{Method: "GET", Path: "/api/wallet/reveal", Description: "Reveal password for a credential (require: user_id, id)"},
		{Method: "POST", Path: "/api/wallet/import", Description: "Import passwords from a Chrome-based browser CSV export"},
		{Method: "GET", Path: "/api/wallet/{id}", Description: "Get wallet entry by ID"},
		{Method: "PUT", Path: "/api/wallet/{id}", Description: "Update wallet entry by ID"},
		{Method: "DELETE", Path: "/api/wallet/{id}", Description: "Delete wallet entry by ID"},
		{Method: "GET", Path: "/api/users", Description: "Get all users"},
		{Method: "POST", Path: "/api/users", Description: "Create a new user"},
		{Method: "GET", Path: "/api/users/{id}", Description: "Get user by ID"},
		{Method: "DELETE", Path: "/api/users/{id}", Description: "Delete user by ID"},
		{Method: "GET", Path: "/api/prompts", Description: "List prompts (filters: user_id, q)"},
		{Method: "POST", Path: "/api/prompts", Description: "Create a prompt"},
		{Method: "GET", Path: "/api/prompts/{id}", Description: "Get prompt by ID"},
		{Method: "PUT", Path: "/api/prompts/{id}", Description: "Update prompt by ID"},
		{Method: "DELETE", Path: "/api/prompts/{id}", Description: "Delete prompt by ID"},
		{Method: "GET", Path: "/api/prompts/search", Description: "Fuzzy search prompts (params: user_id, q, limit)"},
		{Method: "GET", Path: "/api/quiz/questions", Description: "List questions (filters: user_id, type, difficulty, tag (repeatable), subject, topic, sub_topic, q, limit, offset)"},
		{Method: "POST", Path: "/api/quiz/questions", Description: "Create a question"},
		{Method: "GET", Path: "/api/quiz/questions/{id}", Description: "Get question by ID"},
		{Method: "PUT", Path: "/api/quiz/questions/{id}", Description: "Update question by ID"},
		{Method: "DELETE", Path: "/api/quiz/questions/{id}", Description: "Delete question by ID"},
		{Method: "POST", Path: "/api/quiz/questions/{id}/image", Description: "Upload an image for a question (multipart: file)"},
		{Method: "GET", Path: "/api/quiz/questions/{id}/image", Description: "Get a question's image"},
		{Method: "GET", Path: "/api/quiz/cards", Description: "List review cards (filters: user_id, tag (repeatable), limit, practice=true to include scheduled cards, mode=new|skipped|hard)"},
		{Method: "POST", Path: "/api/quiz/cards/{id}/review", Description: "Record a card review (body: user_id, rating)"},
		{Method: "POST", Path: "/api/quiz/cards/{id}/skip", Description: "Persist a skip event without rescheduling (body: user_id)"},
		{Method: "POST", Path: "/api/quiz/papers", Description: "Generate and persist a sectioned question paper (body: user_id, title, sections)"},
		{Method: "GET", Path: "/api/quiz/papers", Description: "List generated papers (filters: user_id, limit, offset)"},
		{Method: "GET", Path: "/api/quiz/papers/{id}", Description: "Get a paper with its full question list"},
		{Method: "DELETE", Path: "/api/quiz/papers/{id}", Description: "Delete a paper"},
		{Method: "GET", Path: "/api/quiz/tags", Description: "Get distinct tag/subject/topic/sub_topic vocabulary (filter: user_id)"},
		{Method: "GET", Path: "/api/quiz/stats", Description: "Get question counts grouped by type, difficulty, and tag (filter: user_id)"},
		{Method: "GET", Path: "/api/users/{id}/quiz-settings", Description: "Get a user's quiz scheduler (sm2 or fsrs)"},
		{Method: "POST", Path: "/api/users/{id}/quiz-settings", Description: "Set a user's quiz scheduler (body: scheduler; sm2 | fsrs)"},
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(routes)
}
